---
# ====== Application: Demonstration - EMP / DEPT =============
identification: 
  name: Demonstration - EMP / DEPT
  alias: DEMONSTRATION-EMP-DEPT
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: false
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 117785342188843253042

authorization: 
  authorization-scheme: Reader Rights # 117785638703369253260
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: WKSP_APEXTRAININGJAKEHOUGHTON

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Demonstration - EMP / DEPT

progressive-web-app: 
  enable: true
  installable: true
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: true
  pwa-push-notifications-credentials: App 114960 Push Notifications Credentials # 117785913241376254092

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 117785342998922253043

navigation-bar: 
  implementation: List
  list: Navigation Bar # 117785633455884253254
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: true
  auto-dismiss-success-messages: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Demonstration - EMP / DEPT

component-settings: 
- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 24942039364306103
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  settings: 
    attribute-1: separated

  subscription: 
    version-number: 15537094414419

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 48585091586309660
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 15537094442861

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 72228011767312878
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 15537094466587

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 117785338847185253040
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 15532690655929

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 117785339167376253041
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER:TODAY-BUTTON'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 15532690655941

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 117785339485732253041
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 15532690655953

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 117785339732797253041
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 15532690655959

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 117785340046565253041
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 15532690655969

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 117785340390023253041
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH_CB

  subscription: 
    version-number: 15532690655977

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 117785340663498253041
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 15532690655984

- # ====== Component Setting: NATIVE_IR ========================
  id: 117785340938641253042
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 15532690655991

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 117785341272241253042
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 15532690655991

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 117785341599310253042
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 15532690655998

application-settings: 
- # ====== Application Setting: FEEDBACK_ATTACHMENTS_YN ========
  id: 117785639678970253261
  identification: 
    name: FEEDBACK_ATTACHMENTS_YN

  value: 
    value: Y
    required: false

  advanced: 
    valid-values: Y, N
    on-upgrade-keep-value: true

  subscription: 
    version-number: 15532690664699

  configuration: 
    build-option: 'Feature: Feedback' # 117785636101759253258

- # ====== Application Setting: ACCESS_CONTROL_SCOPE ===========
  id: 117785639930793253261
  identification: 
    name: ACCESS_CONTROL_SCOPE

  value: 
    value: ACL_ONLY
    required: false

  advanced: 
    valid-values: ACL_ONLY, ALL_USERS
    on-upgrade-keep-value: true

  subscription: 
    version-number: 15532690664723

  configuration: 
    build-option: 'Feature: Access Control' # 117785635925623253258

  comments: 
    comments: The default access level given to authenticated users who are not in the access control list

